name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy to Server
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.SERVER_HOST }}
            port: ${{ secrets.SERVER_PORT }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd ~/wanna-trip-server/
              git pull origin main
              npm install
              pm2 restart "wanna-trip-server"